### ISSUE TITLE
能不能给几个运行初始参数案例

### ISSUE THREAD

**Issue by cuichangfei** [KoutaTakeshi/Parachute-opening-process-calculation-software#1]
作者的Email，有些问题想请教作者

**Comment by KoutaTakeshi** [comment]
![算例](https://user-images.githubusercontent.com/50045691/172792449-c050c0c9-ee07-4530-957c-ab0aaf7d0fc5.jpg)
最终的轨迹图像的计算程序有一些问题，所以轨迹仅供参考一个大致运动趋势。
最大拉直力和经验公式误差10%，最大开伞动载和经验公式误差20%。

**Comment by cuichangfei** [comment]
谢谢，我发现这个没有完整的轨迹曲线，我想要从开始到落点的完整曲线，改一下程序应该能获得把

**Comment by KoutaTakeshi** [comment]
https://github.com/KoutaTakeshi/Parachute-calculation-software/blob/c65aeb64511bfb4c9b9e90198062f57cb4051fd2/main.m#L60
对，直接改tm后的求解时间长度就行，不过要把高度改小，不然需要很长时间才能到达地面。
由于我的主伞位置是根据载荷位置反推的，如果你发现过程中主伞位置上升（实际应该是一直下降），需要修改算例，增大载荷质量、减小伞衣直径或增大开伞速度，正确的轨迹图应该像这样：
![充气过程轨迹](https://user-images.githubusercontent.com/50045691/172820937-b0dc2ddc-8c0e-4016-8219-53dbca12fd62.jpg)
这里我修改了降落伞偏转方向，更符合实际一些，把下面代码里v1(1 : tmax - 1, 2)和Lxt前面的+改为-就行。
https://github.com/KoutaTakeshi/Parachute-calculation-software/blob/c65aeb64511bfb4c9b9e90198062f57cb4051fd2/main.m#L34
https://github.com/KoutaTakeshi/Parachute-calculation-software/blob/c65aeb64511bfb4c9b9e90198062f57cb4051fd2/main.m#L64
