### ISSUE TITLE
Hello, I have a question

### ISSUE THREAD

**Issue by walkerjohnsonofficial** [KoutaTakeshi/Parachute-opening-process-calculation-software#2]
在学习的过程，发现有个过程，不知道是否正确，有可能是我没理解到位。这段代码：
elseif v(2) <= (Lsh+b)
        dv(1) = densystar * dv(2);
        dv(3) = g * sind(v(5)) - ((0.5 * den * v(3)^2 * CAw) + densystar * (Lxt - v(2)) * ((v(3) - v(4))^2)) / (mw + v(1));
这个过程中“Lxt - v(2)”即为用总长度减掉当下的长度，剩余的长度不是伞底宽度所剩下的其余量，还包括了伞衣的D0/2.我是不是理解错了。。。请教。是否方便邮件沟通？109443322@163.com 谢谢！

**Comment by KoutaTakeshi** [comment]
https://github.com/KoutaTakeshi/Parachute-calculation-software/blob/032b8acca9837ea787ce9a32c5b05524b8d36438/main.m#L11-L12
整个系统长度仅由伞绳长度Lsh和伞衣长度D0/2构成，伞衣底边的宽度b其实是包含在伞衣的D0/2内的

**Comment by walkerjohnsonofficial** [comment]
感谢你的回答，我在研究的过程发现了这一点，正好你也回答了，哈哈哈哈
